### ISSUE TITLE
Blender 2.71 cannot connect to render master

### ISSUE THREAD

**Issue by matthiasbalke** [rndevfx/docker-blender-render-cluster#1]
Can you tell me if the blender version used for this docker image is compatible with Blender 2.71?

I can connect to the render master webapp, but Blender refuses to connect to the server.

**Comment by cozybuild** [comment]
Currently the Blender version is 2.67 on Docker Hub; 2.77a is building right now.
From now on all Docker images are tagged so you can download (old) Blender Docker images in the future. Blender 2.71 is not supported; I'm sorry for that.
