### ISSUE TITLE
Update to Blender 2.78

### ISSUE THREAD

**Issue by cozybuild** [rndevfx/docker-blender-render-cluster#2]
Currently there is an open pull request at https://github.com/gentoo/gentoo/pull/2531 for Blender 2.78 which improves the package in several ways (thanks to @dracwyrm). I'll wait until the review process is done and will use the ebuild from the official Gentoo testing repo.

**Comment by dracwyrm** [comment]
The new ebuild now has headless use flag which reduces the depends and makes it more suitable for a render farm. It's a bit experimental at the moment, so feedback is greatly welcomed on that, like if we could use even fewer depends or need to enable more features. :)

Also, three new packages being added which add some nice rendering options for particles and decreasing render time.

If you want to start prep work, you can practice with the new ebuilds from here:
https://github.com/dracwyrm/gentoo-ebuilds

More features will hopefully come later as well. You have a great project here. We were hoping that Gentoo and Blender would be used as a Render Farm.

**Comment by cozybuild** [comment]
Yes, I'm using your repo on my local machine since a few weeks and I really like your work (that's what I said in #gentoo irc :+1: )

EDIT: I'm still using 2.77 on my production servers and 2.78 just for "testing" on my local machine. Waiting for 2.78a :smile:

**Comment by dracwyrm** [comment]
I got your message on IRC. :) Thanks. I need all the testers I can get, especially when it comes to Render Farms. I want to make that a solid feature.

Cheers.

**Comment by dracwyrm** [comment]
Just to let you know, it's all in the tree now:
https://github.com/gentoo/gentoo/commit/74468a07030339cc74cab6a2382167d7bf3ebf80
https://github.com/gentoo/gentoo/commit/8e68c375c5637e926b7a16c2b3196ee7bf0cee38
https://github.com/gentoo/gentoo/commit/6af03d83c698063b3328230c2106eab4134a4470
https://github.com/gentoo/gentoo/commit/cb021f3026afbe8c0acf42de427b209b72e69dc3

Thanks for testing when it was still overlay status. The more eyes on something, the better.

Cheers,
Jon

**Comment by cozybuild** [comment]
2.78a is released (not official but it's distributed to all mirrors currently) and then I'll update the containers :smile:

**Comment by dracwyrm** [comment]
@rndevfx If you want, you can try the 2.78a ebuild:
https://github.com/dracwyrm/gentoo-ebuilds/tree/master/media-gfx
I can't push it to portage until release in case they change the tarball, which is known to happen. :)

Current change log for the A release:
https://wiki.blender.org/index.php/Dev:Ref/Release_Notes/2.78/Bug_Fixes#.27A.27_Corrective_Release

**Comment by cozybuild** [comment]
Thank you @dracwyrm for your great work at Gentoo!
