### ISSUE TITLE
images are not listed on docker hub

### ISSUE THREAD

**Issue by matthiasbalke** [rndevfx/docker-blender-render-cluster#3]
When trying to list the tags via `curl https://index.docker.io/v1/repositories/d3v0x/blender-render-cluster/tags` I always get "ressource not found" as response.

Also I cannot find your repository on docker hub. Did you remove/rename it?

If you need help setting the docker hub repo up again, I'm willing to contribute some time and support to get it back online.

**Comment by cozybuild** [comment]
Yes, the images are removed temporarily. Currently I've got some Gentoo-build problems and I didn't want to serve images with security issues. But they will be back soon!

**Comment by sachk** [comment]
It's been a few months, are they coming back?

**Comment by cozybuild** [comment]
The images are back and I'll push some fixes for the project today. Blender 2.79 is coming soon - I'm waiting for https://bugs.gentoo.org/630820

Thanks to @dracwyrm for the great work!!

**Comment by matthiasbalke** [comment]
@rndevfx There is only one image (latest) on docker hub: https://hub.docker.com/r/d3v0x/blender-render-cluster

Please provide version tags, based on the blender version used, so one can choose which version to use.

**Comment by cozybuild** [comment]
Tags are back as well :) Thanks for reporting!
